# Generated by Django 5.0.2 on 2024-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('BOOK_TITLE', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('BOOK_PAGES', models.IntegerField()),
                ('BOOK_AUTHOR', models.CharField(max_length=50)),
                ('BOOK_PRICE', models.DecimalField(decimal_places=True, max_digits=10)),
                ('BOOK_CHAPTER', models.CharField(max_length=50)),
            ],
        ),
    ]
